server:
  port: 0

app:
  keycloak:
    url: ${keycloak.url}
    realm: ${keycloak.realm}
    client:
      frontend:
        id: ${keycloak.client.frontend.id}
      backend:
        id: ${keycloak.client.backend.id}
        secret: ${keycloak.client.backend.secret}


spring:
  application:
    name: user-service