server:
  port: 0

app:
  config-service:
    url: http://localhost:8888

spring:
  application:
    name: stock-service
  config:
    import: configserver:${app.config-service.url}
  cloud:
    config:
      uri: ${app.config-service.url}
      fail-fast: true

logging:
  level:
    ru.dreadblade.stockmarket.stockservice: TRACE
