version: '3.9'
name: stock-market
services:
  elasticsearch:
    image: elasticsearch:8.4.3
    container_name: elasticsearch
    networks:
      - stock-market-network
    ports:
      - "9200:9200"
    restart: on-failure
    environment:
      ES_JAVA_OPTS: -Xms256m -Xmx256m
      ELASTIC_PASSWORD: password
      discovery.type: single-node
      xpack.security.enabled: false

  kibana:
    image: kibana:8.4.3
    container_name: kibana
    networks:
      - stock-market-network
    ports:
      - "5601:5601"
    restart: on-failure
    depends_on:
      - elasticsearch
    environment:
      KIBANA_SYSTEM_PASSWORD: password
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro

  logstash:
    image: logstash:8.4.3
    container_name: logstash
    networks:
      - stock-market-network
    ports:
      - "5000:5000"
      - "5044:5044"
      - "9600:9600"
    restart: on-failure
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
      LOGSTASH_INTERNAL_PASSWORD: password
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/:ro

networks:
  stock-market-network:
    name: stock-market-network