version: '3.9'
name: stock-market
services:
  stock-service-postgresql:
    image: postgres:14
    container_name: stock-service-postgresql
    networks:
      - stock-market-network
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      POSTGRES_DB: stock_service
      POSTGRES_USER: stock_service_db_user
      POSTGRES_PASSWORD: password

networks:
  stock-market-network:
    driver: bridge