server:
  port: 8080

app:
  config-service:
    url: http://localhost:8888

spring:
  application:
    name: gateway
  config:
    import: configserver:${app.config-service.url}
  cloud:
    config:
      uri: ${app.config-service.url}
      fail-fast: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.security: TRACE
