app:
  services:
    account-service: account-service
    notification-service: notification-service
    order-service: order-service
    payment-service: payment-service
    stock-price-history-service: stock-price-history-service
    stock-price-service: stock-price-service
    stock-service: stock-service
    user-service: user-service

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: ${app.client.stock-market-ng-app.uri}
            allowedHeaders: "*"
            allowedMethods: "*"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.auth-server.issuer-uri}
          jwk-set-uri: ${app.auth-server.jwk-set-uri}