app:
  redis:
    host: localhost
    port: 6379
    password: password
  kafka:
    host: localhost
    port: 9092

spring:
  redis:
    host: ${app.redis.host}
    port: ${app.redis.port}
    password: ${app.redis.password}
  kafka:
    bootstrap-servers: ${app.kafka.host}:${app.kafka.port}
    producer:
      properties:
        spring.json.add.type.headers: false
    consumer:
      auto-offset-reset: earliest
      properties:
        isolation.level: read_committed
