app:
  auth-server:
    protocol: http
    host: localhost
    port: 8180
    realm: stock-market
    issuer-uri: ${app.auth-server.protocol}://${app.auth-server.host}:${app.auth-server.port}/realms/${app.auth-server.realm}
    jwk-set-uri: ${app.auth-server.issuer.uri}/protocol/openid-connect/certs
    client:
      frontend:
        id: stock-market-frontend
      backend:
        id: stock-market-backend
        secret: OItyWT4zcS3LgfXh7IR3jWiSSCzgy3kI