server:
  port: 8888

app:
  config-service:
    user:
      username: user
      password: '{bcrypt}$2a$10$H1dDJ6gGmDjT5mgWweG5xOKOzPucJz0OSycDNcUbF0O5dzweamQfi'

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/services