server:
  port: 0

spring:
  application:
    name: stock-price-service
  redis:
    host: ${redis.host:localhost}
    port: ${redis.port:6379}
    password: ${redis.password:password}
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      properties:
        spring.json.add.type.headers: false
    consumer:
      auto-offset-reset: earliest
      properties:
        isolation.level: read_committed

logging:
  level:
    ru.dreadblade.stockmarket.stockpriceservice: TRACE